### ISSUE TITLE
imapClient.php - problem with iconv() and invalid characters

### ISSUE THREAD

**Issue by nmcgann** [KimNyholm/ubuntu-web-development#3]
There is a long-running php open issue with the `//IGNORE` flag that is needed to stop `iconv()` throwing notice errors on invalid characters.

This workround from the php manual for `iconv()` fixes it (in `EmailGetOne`):
````
  ini_set('mbstring.substitute_character', 'none'); //32 to substitute a space, "none" to remove
  $mail->plainText = mb_convert_encoding($mail->plainText , 'UTF-8', $mail->charset);
  $mail->htmlText  = mb_convert_encoding($mail->htmlText, 'UTF-8', $mail->charset);

````

**Comment by KimNyholm** [comment]
Fixed in commit de0b56985a7492a1e9c710b52fe6c9cd3d2db883
