### ISSUE TITLE
imapClient.php - .txt attachments are also added to the body of the message

### ISSUE THREAD

**Issue by nmcgann** [KimNyholm/ubuntu-web-development#4]
Problem is that a text attachment is correctly detected as an attachment, but also treated as part of the body.

Problem is on line 119 and can be fixed by inhibiting appending data to the body when a filename is found - as shown:
````
if (!empty($data) && empty($filename)){
    if ($type == TYPETEXT) {
 
...etc.
````

**Comment by KimNyholm** [comment]
Fixed in commit 42d4cc5038b50ea71a932c6e527bc032a1650921
