### ISSUE TITLE
problem in saving jpg files

### ISSUE THREAD

**Issue by spjpm** [KimNyholm/ubuntu-web-development#5]
When saving jpg files, the original file is getting saved but the save file is getting saved again with the first letter missing from the file name and the last letter from the extension.

Example if file name is abc.jpg it get saved, but then again another file called bc.jp is getting saved.

**Comment by KimNyholm** [comment]
Could you please elaborate with more details. Where/how are you saving jpgs? If possible step-by-step to reproduce.
